// <auto-generated />
namespace films.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MainTwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MainTwo));
        
        string IMigrationMetadata.Id
        {
            get { return "201902031051030_MainTwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
